### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by armin567ip** [vpnhood/VpnHood#345]
Hi. I tried downloading vpnhoodserver.zip file which is mentioned in here
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Linux-without-ROOT-access
but it retures Not Found.
Also can you please give us a more complete guide on how to install VPNHood on the server with no root access. and also teaching us how to install .net runtime. cause I guess I downloaded the wrong version of that too.

**Comment by trudyhood** [comment]
Thank you for reporting. I fixed the outdated document. You don't need to install .NET runtime anymore. Please follow the document and let me know if you have any questions.

**Comment by armin567ip** [comment]
Thank you so much for checking this case and updating the steps. But actually it's still not working. let me explain everything. I downloaded and extracted the file. I'm using x62 BTW. then after I noticed there is actually no VpnHoodServer/launcher
directory. after I extracted the file there was a only a folder called "v2.9.370" then inside that there was only a folder called "publish_info" and lot of other files. so then I runned this command "chmod +x VpnHoodServer" and then after that when I entered the "ls" command. the VpnHoodServer file was at green color so I guess that means that the first command was successful. But then after I runned this command "VpnHoodServer gen" it gave me "bash: VpnHoodServer: command not found".
I also wanted to use the VPN Hood access server. but it keeps giving me "There was an error trying to log you in: ''
I also used VPN but the error is still there. Please recheck and help me 🙏❤

**Comment by armin567ip** [comment]
Great. but this command is showing an error:
GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E

**Comment by armin567ip** [comment]
Actually I'm using a typical shared hosting environment called cPanel. You might be familiar with cPanel. its simply an environment for deploying websites or projects. But it also has a terminal so you can run some codes or anything you want but it is not root access and has many limitations. 
So I runned this command to get my linux version "uname -a
"
it returns "Linux ws.dnsprotection.me 4.18.0-425.10.1.lve.el8.x86_64 #1 SMP Wed Jan 25 12:10:58 EST 2023 x86_64 x86_64 x86_64 GNU/Linux".
Actually I also did the steps in another server (not cPanel) and it did work.  So i guess the problem is the limitations on cPanel. But it would be great if you please check this case and make us a guide on how to install VPN Hood on cPanel 🙏❤

**Comment by armin567ip** [comment]
> what is your linux version?

Actually I'm using a typical shared hosting environment called cPanel. You might be familiar with cPanel. its simply an environment for deploying websites or projects. But it also has a terminal so you can run some codes or anything you want but it is not root access and has many limitations.
So I runned this command to get my linux version "uname -a
"
it returns "Linux ws.dnsprotection.me 4.18.0-425.10.1.lve.el8.x86_64 https://github.com/vpnhood/VpnHood/discussions/1 SMP Wed Jan 25 12:10:58 EST 2023 x86_64 x86_64 x86_64 GNU/Linux".
Actually I also did the steps in another server (not cPanel) and it did work. So i guess the problem is the limitations on cPanel. But it would be great if you please check this case and make us a guide on how to install VPN Hood on cPanel 🙏❤

**Comment by trudyhood** [comment]
I create a feature for it, but this feature is not on our table now. It must be possible as VpnHoodServer just relies on .NET Standard 2.1 (the most compatible .NET framework). However, it needs some adjustment and debugging. We would be grateful if you share with us any progress you have.
Feature: #348

**Comment by armin567ip** [comment]
Hi bro. I want to report a problem. I got myself a root access VPS server and I tried the method of installing without root. it was all good and it gave me the access key. but when I entered the access key and tried to connect to the server it says: The server actively refused the connection. it says something like this. I did everything correctly. its just a problem that you have to fix. BTW I have to mention that you have to put cPanel installation a top priority and make a guide on how to install VPN Hood on cPanel . Cause it is the only way we can get servers with no root access . otherwise what is the benefit of this feature. there is no provider that give you server with no root. its only cPanel servers

**Comment by trudyhood** [comment]
>> The server actively refused the connection
Please send us the server log. You can find it in the directory called "storage" within the VpnHoodServer directory.

>> What is the benefit of this feature
This feature provides the advantage of our core not relying on root access. A non-admin user can run it in their user environment. However, as you mentioned, cPanel support is necessary to ensure ease of use and compatibility with more platforms, especially when the user doesn't have access to the console.

**Comment by armin567ip** [comment]
Actually I don't have access to that server anymore to get you the logs. But I'll do my best. 
Also I have to mention that cPanel does have a terminal but it is not root access. However it depends on the hosting provider. Some providers disable terminal.
It would be really great if you could develop VPN Hood on languages like Python, PHP, NodeJS or Ruby. Cause cpanel supports all these languages completely. It allows you to run python scripts even without using the terminal.

**Comment by armin567ip** [comment]
Actually I don't have access to that server anymore to get you the logs. But I'll do my best.
Also I have to mention that cPanel does have a terminal but it is not root access. However it depends on the hosting provider. Some providers disable terminal.
It would be really great if you could develop VPN Hood on languages like Python, PHP, NodeJS or Ruby. Cause cpanel supports all these languages completely. It allows you to run python scripts even without using the terminal.

**Comment by armin567ip** [comment]
[logs.zip](https://github.com/vpnhood/VpnHood/files/12072121/logs.zip)

Here bro. the logs.
Let me explain exactly what i do .
First i download the file and i extract it. then I go to that directory and make the file executable "chmod +x VpnHoodServer"

but when I run this command "./VpnHoodServer". it will start the server but it will put me in a position that I can not type anything. so i had to press ctrl + C to be able to type again . so then I entered "./VpnHoodServer gen" to generate an access key and again I entered "./VpnHoodServer" to start the server. and it is working just fine but the only problem is if I close the terminal window the VPN will not work.

**Comment by armin567ip** [comment]
> > The server actively refused the connection
> 
> Please send us the server log. You can find it in the directory called "storage" within the VpnHoodServer directory.
> 
> > What is the benefit of this feature
> 
> This feature provides the advantage of our core not relying on root access. A non-admin user can run it in their user environment. However, as you mentioned, cPanel support is necessary to ensure ease of use and compatibility with more platforms, especially when the user doesn't have access to the console.

[logs.zip](https://github.com/vpnhood/VpnHood/files/12072121/logs.zip)

Here bro. the logs.
Let me explain exactly what i do .
First i download the file and i extract it. then I go to that directory and make the file executable "chmod +x VpnHoodServer"

but when I run this command "./VpnHoodServer". it will start the server but it will put me in a position that I can not type anything. so i had to press ctrl + C to be able to type again . so then I entered "./VpnHoodServer gen" to generate an access key and again I entered "./VpnHoodServer" to start the server. and it is working just fine but the only problem is if I close the terminal window the VPN will not work.

**Comment by trudyhood** [comment]
I am not sure. look at this topic:
https://superuser.com/questions/96660/how-can-i-keep-a-process-alive-after-closing-the-putty-session

If you find a robust way, let us know

**Comment by armin567ip** [comment]
Bro its not that. I don't wanna keep the putty window alive. Just try it yourself you'll undertands what I mean. It's just a simple fix in code. Its not a complicated thing.

**Comment by armin567ip** [comment]
All I'm saying is that. When it gives me the access key. It does not release the curser . I can not type anything.you understand me.

**Comment by trudyhood** [comment]
Dear friend, You said **"the only problem is if I close the terminal window, the VPN will not work."**
So I sent you your reply to find a way to keep the process open.

Regarding **" When it gives me the access key. It does not release the curser"**, I tried it many times. Unfortunately, it was working for me, so I couldn't simulate the issue to solve it. Ensure the server is not running (press ctrl+c) before executing the gen command. You can also open another session if you need to execute Gen without stopping the server.
