### ISSUE TITLE
VPN connection drops

### ISSUE THREAD

**Issue by Jeje292** [vpnhood/VpnHood#508]
Hello,

I can see the VPN Client keep disconnect/reconnect regularly when I'm downloading torrent.

Windows client : 4.3.485.109 (UDP Mode)
VpnHoodServer : Docker on VPS (default config & last version)

How can I diagnose that ?
I tried diagnose mode, without success and without knowing where to look

Logfile in attachment

Thank you for your help !
[log.zip](https://github.com/vpnhood/VpnHood/files/14894343/log.zip)

Edit : 

When I close qBittorrent, the VpnHood client disconnect a time and connection losses seem to not appear again (after waiting 10 minutes).
When I reopen qBitorrent, one minute later VpnHood disconnect and reconnect, and continue to disconnect/reconnect regularly with very low traffic (less than 0,1 Mbps in up/down).

**Comment by trudyhood** [comment]
Many people have reported that this issue has been solved in v6.0.676
Please comment on this closed issue if the problem exists so I can reopen it.

**Comment by Jeje292** [comment]
Hello @trudyhood 
I tested last version [Windows client 7.0.708 & Linux Server v7.1.711]
I still see disconnections/reconnections on client, even though it seems to be more stable.

**Comment by trudyhood** [comment]
does it really get disconnected or it sometimes shows connecting?
can you send me a lot from client

Best,
Trudy
VpnHood

**Comment by trudyhood** [comment]
Just client side, send me a diagnosis.
 Actually, vpnhood never gets disconnected or reconnected; it remains idle for some minutes in the connecting state till disconnected completely. When the connection becomes unstable, it displays "Connecting....", but perhaps we should change it to "Poor connection..."
